name: Create New Discussion

on:
  workflow_dispatch:

jobs:
  create-new-discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get Discussion IDs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X GET \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer <YOUR-TOKEN>" \
          https://api.github.com/repos/h602119/Goodtech_Praksis_workflow_discussion/discussions/categories


      - name: Create a new discussion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: "Automated Discussions"
          BODY: "Hello World"
        run: |
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"title\": \"$TITLE\", \"body\": \"$BODY\", \"category_id\": \"<CATEGORY_ID>\"}" \
            https://api.github.com/repos/${{ github.repository }}/discussions
