name: Create New Discussion

on:
  workflow_dispatch:

jobs:
  create-new-discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Manually read the id from the JSON 
      # api.github.com/h602119/Goodtech_Praksis_workflow_discussion/
      # api.github.com/{owner}/{repo}/discussions
      # Example id : DIC_kwDONnjXbM4Cl942

      - name: Testing new RepoId Fetch
        id: new-fetch
        env:
          USER: h602119
          REPO: Goodtech_Praksis_workflow_discussion
          GH_TOKEN: ${{ github.token }}
        run: |
          repo_id=$(gh api -H "Accept: application/vnd.github+json" repos/$USER/$REPO | jq .id)
          echo "This is the repo id: $repo_id"

      - name: Fetch repository ID via GraphQL
        id: fetch-repo-id
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "::set-output name=repo_id::$(curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"query":"query { repository(owner: \"h602119\", name: \"Goodtech_Praksis_workflow_discussion\") { id } }"}' \
          https://api.github.com/graphql | jq -r '.data.repository.id')"

      - name: Create a new discussion
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CATEGORY_ID: "DIC_kwDONnjXbM4Cl942"
          TITLE: "Hello World"
          BODY: "Hello World"
          USER: h602119
          REPO: Goodtech_Praksis_workflow_discussion
        run: |
          repo_id=$(gh repo view --json id --jq .id)
          
          response=$(curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"query\": \"mutation { createDiscussion(input: { repositoryId: \\\"$repo_id\\\", title: \\\"$TITLE\\\", body: \\\"$BODY\\\", categoryId: \\\"$CATEGORY_ID\\\" }) { discussion { id title url } } }\"
            }" \
            https://api.github.com/graphql)

          if echo "$response" | grep -q '"errors"'; then
            error_message=$(echo "$response" | jq -r '.errors[0].message')
            echo "Error: Failed to create discussion. $error_message"
            exit 1
          fi
          echo "Discussion created successfully."
