name: Create New Discussion

on:
  #workflow_dispatch:
  push:


jobs:
  create-new-discussion:
    runs-on: ubuntu-latest

    steps:

      # When creating a new discussion, it needs to be published to a category, using its unique id as identifier.
      - name: Fetch and parse discussion categories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "query { repository(owner: \"h602119\", name: \"Goodtech_Praksis_workflow_discussion\") { discussionCategories(first: 10) { nodes { id name description } } } }"
            }' \
            https://api.github.com/graphql | jq -r '.data.repository.discussionCategories.nodes[] | "\(.id): \(.name)"'

      # Automatically gets the id of the repository, needed when publishing a new discussion.
      - name: Fetch repository ID via GraphQL
        id: fetch-repo-id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=repo_id::$(curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"query":"query { repository(owner: \"h602119\", name: \"Goodtech_Praksis_workflow_discussion\") { id } }"}' \
          https://api.github.com/graphql | jq -r '.data.repository.id')"


      - name: Create a new discussion via GraphQL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY_ID: "DIC_kwDONnjXbM4Cl2Qi"
          TITLE: "Hello World"
          BODY: "Hello World"
        run: |
          repo_id="${{ steps.fetch-repo-id.outputs.repo_id }}"
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"query\": \"mutation { createDiscussion(input: { repositoryId: \\\"$repo_id\\\", title: \\\"$TITLE\\\", body: \\\"$BODY\\\", categoryId: \\\"$CATEGORY_ID\\\" }) { discussion { id title url } } }\"
            }" \
            https://api.github.com/graphql



