name: Automate with GraphQL

on:
  push:

jobs:
  query-graphql:
    runs-on: ubuntu-latest

    steps:

      - run: echo ${{github.actor}}
      - run: echo ${{github.repository}}
    
      - name: Fetch and parse discussion categories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "query { repository(owner: \"h602119\", name: \"Goodtech_Praksis_workflow_discussion\") { discussionCategories(first: 10) { nodes { id name description } } } }"
            }' \
            https://api.github.com/graphql | jq -r '.data.repository.discussionCategories.nodes[] | "\(.id): \(.name)"'
